language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t lokilokesh/docker-react .

script:
  - docker run lokilokesh/docker-react npm test -- --coverage --watchAll=false